CREATE TABLE PERSONNE (AGE INTEGER, NOM VARCHAR NOT NULL, PRENOM VARCHAR NOT NULL, CHIEN_ID INTEGER, PRIMARY KEY (NOM, PRENOM))
CREATE TABLE CHIEN (ID INTEGER NOT NULL, NOM VARCHAR, PRIMARY KEY (ID))
ALTER TABLE PERSONNE ADD CONSTRAINT FK_PERSONNE_CHIEN_ID FOREIGN KEY (CHIEN_ID) REFERENCES CHIEN (ID)
